version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/New_York
    open-pull-requests-limit: 100
    reviewers:
      - "Shopify/sorbet"
    ignore:
      - dependency-name: "@types/vscode"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
