version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/New_York
    open-pull-requests-limit: 100
    reviewers:
      - "Shopify/ruby-dx"
    ignore:
      - dependency-name: "@types/vscode"
      - dependency-name: "eslint"
        versions: [">= 0.9.0"] # blocked by https://github.com/Shopify/web-configs/issues/425
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
