name: vscode-shopify-ruby

type: nodejs

up:
  - node:
      yarn: true
      version: 18.15.0

commands:
  package: "yarn run package"
  compile: "yarn run compile"
  lint: "yarn run lint"
  style: "yarn run format"
  test: "yarn run test"
